if(NOT TARGET real-time-monitor::rtm_recorder)
    add_executable(real-time-monitor::rtm_recorder IMPORTED GLOBAL)
    set(_rtm_recorder_default_set FALSE)
    foreach(_cfg RELEASE DEBUG RELWITHDEBINFO MINSIZEREL)
        set(_pf "${real-time-monitor_PACKAGE_FOLDER_${_cfg}}")
        if(NOT _pf)
            continue()
        endif()
        set(_exe "${_pf}/bin/rtm_recorder${CMAKE_EXECUTABLE_SUFFIX}")
        set_property(TARGET real-time-monitor::rtm_recorder
            PROPERTY IMPORTED_LOCATION_${_cfg} "${_exe}")
        if(NOT _rtm_recorder_default_set)
            set_property(TARGET real-time-monitor::rtm_recorder
                PROPERTY IMPORTED_LOCATION "${_exe}")
            set(_rtm_recorder_default_set TRUE)
        endif()
    endforeach()
    unset(_rtm_recorder_default_set)
    unset(_pf)
    unset(_exe)
endif()
