name: PR build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Install OS dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libwayland-dev libxkbcommon-dev

    - name: Setup build env
      run: |
        ./setup_build.sh ${{github.workspace}}/build

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/build/toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build build

    - name: Test
      run: |
        ctest --test-dir build --output-on-failure

    - name: Upload Build Artifact
      if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: build-linux
        path: build/
        retention-days: 1

  build-conan-package:
    needs: build
    name: Build Conan Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-linux
        path: build/

    - name: Determine version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "PKG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "PKG_VERSION=${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: Conan Create
      run: |
        conan create conan/all --build=missing --version ${{ env.PKG_VERSION }} -pr:b build/profile.txt -pr:h build/profile.txt

    - name: Export Conan package
      run: |
        conan cache save "real-time-monitor/${{ env.PKG_VERSION }}:*" --file real-time-monitor-${{ env.PKG_VERSION }}-linux-x86_64.tgz

    - name: Upload Conan package artifact
      uses: actions/upload-artifact@v4
      with:
        name: conan-package
        path: real-time-monitor-${{ env.PKG_VERSION }}-linux-x86_64.tgz
        if-no-files-found: error
